### ISSUE TITLE
Does not work with Hexo v5

### ISSUE THREAD

**Issue by JamesSingleton** [hexojs/hexo-generator-alias#56]
It would be nice if this worked with the latest version of Hexo.

**Comment by SukkaW** [comment]
```bash
npm install hexo-generator-alias@latest --save
```

Then it should works fine then.

**Comment by SukkaW** [comment]
Closes as [1.0.0](https://github.com/hexojs/hexo-generator-alias/releases/tag/1.0.0) has already been released.

**Comment by JamesSingleton** [comment]
Does it no longer support the `_config.yml` file then? I just tested with that and it doesn't work.

**Comment by JamesSingleton** [comment]
Also, the `README` says 3&4 even after `v1` being released.

**Comment by JamesSingleton** [comment]
Both within a file that is `index.md` I have an alias like

```
alias:
 - v4/guide/index.html
 - v2/guide/index.html
```

And in the `_config.yml` I tried

```
alias:
  v2/guide/index.html: v4/guide/index.html
  v2/guide/index.html: index.html
```

This used to work in v4 of hexo but no longer does in v5.
