### ISSUE TITLE
New version needs to be pushed to npm

### ISSUE THREAD

**Issue by dsolovay** [hexojs/hexo-generator-alias#7]
npm still lists version 0.1.0 as current: https://www.npmjs.com/package/hexo-generator-alias

> 0.1.0 is the latest of 2 releases

Please issue an `npm publish` command to update npm to the current version.
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by Xuanwo** [comment]
@tommy351

**Comment by laurentkempe** [comment]
You can also install it directly from github repo with the following command

    npm install git+https://github.com/hexojs/hexo-generator-alias.git --save

**Comment by curbengh** [comment]
New version needs to be published for hexo@3 compatibility.
Once this issue is closed, https://github.com/hexojs/hexo-generator-alias/issues/1 and https://github.com/hexojs/hexo-generator-alias/pull/2 can be closed too.

**Comment by tomap** [comment]
I publushed a pre release
https://www.npmjs.com/package/hexo-generator-alias/v/1.0.0-rc1
Anyone wants to validate?

**Comment by curbengh** [comment]
I'll do it.
If there is no issue, release v1 after hexo v4 is published.

**Comment by tomap** [comment]
Why after?

**Comment by curbengh** [comment]
Perhaps we should the discussion about plugin release to https://github.com/hexojs/hexo/issues/3508, https://github.com/orgs/hexojs/teams/core/discussions/5 or https://github.com/hexojs/hexo/issues/3630. My understanding is that plugins (which drops node 6) should be released after hexo@4 or at least together.

**Comment by curbengh** [comment]
> I publushed a pre release
> https://www.npmjs.com/package/hexo-generator-alias/v/1.0.0-rc1
> Anyone wants to validate?

I can confirm it works. But before v1.0, I want to update the readme to clarify the function.
